//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yemekane_Otomasyon_deneme2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hareketler
    {
        public int ID { get; set; }
        public string Tckimlikno { get; set; }
        public Nullable<System.DateTime> Donem { get; set; }
    }
}
