//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yemekane_Otomasyon_deneme2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YemekhaneotomasyonuEntities1 : DbContext
    {
        public YemekhaneotomasyonuEntities1()
            : base("name=YemekhaneotomasyonuEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Hareketler> Hareketler { get; set; }
        public virtual DbSet<İzinler> İzinler { get; set; }
        public virtual DbSet<Üye> Üye { get; set; }
    }
}
